language: cpp
compiler:
  #  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install rake bison git gperf g++-4.8 libev-dev libevent-dev libjansson-dev libjemalloc-dev libxml2-dev libssl-dev zlib1g-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi; fi
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl libev; fi
  - git clone https://github.com/h2o/qrintf.git
  - cd qrintf
  - sudo make install PREFIX=/usr/local
  - cd ..
  - nvm install 0.12
  - nvm use 0.12
  - npm install -g mocha
script:
  - rvm use 2.2
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -f ../build_config.rb .
  - rake
  - cd ..
  - rake
  - export CXX=g++
  - export CC=gcc
  - npm install ref node-ffi/node-ffi#gh-241
  - mocha --reporter spec --timeout 15000
