language: cpp
compiler:
  #  - gcc
  - clang
os:
  - linux
  - osx
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install rake bison git gperf g++-4.8 libev-dev libevent-dev libjansson-dev libjemalloc-dev libxml2-dev libssl-dev zlib1g-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi; fi
  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/dupes; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install openssl libev zlib; fi
  - curl -L git.io/nodebrew | perl - setup
  - export PATH=$HOME/.nodebrew/current/bin:$PATH
  - git clone https://github.com/h2o/qrintf.git
  - cd qrintf
  - sudo make install PREFIX=/usr/local
  - cd ..
  - nodebrew install-binrary 5.2.0
  - nodebrew use 5.2.0
  - npm install -g mocha
script:
  - rvm use 2.2
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -f ../build_config.rb .
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CXXFLAGS="-I/usr/local/opt/libev/include"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export CFLAGS="-I/usr/local/opt/libev/include -I/usr/local/opt/openssl/include"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export LDFLAGS="-L/usr/local/lib -L/usr/local/opt/openssl/lib"; fi
  - rake
  - cd ..
  - rake
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-4.8 -std=c++11"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CC=gcc; fi
  - npm install node-ffi/node-ffi#gh-241
  - mocha --reporter spec --timeout 15000
